name: FastAPI test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ci_cd/test_app/requirements.txt

      - name: Start Backend Server
        run: |
          cd ./ci_cd/test_app
          uvicorn main:app --reload &

      #add some test
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov httpx
          pytest
